# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  prod-mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: SomePassword
      MYSQL_DATABASE: cards
      MYSQL_USER: cardsadmin
      MYSQL_PASSWORD: CardsPass
    volumes:
      - 'mariadb_data:/var/lib/mysql'
    ports:
      - "3306:3306"
  test-mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: SomePassword
      MYSQL_DATABASE: cards
      MYSQL_USER: cardsadmin
      MYSQL_PASSWORD: CardsPass
    volumes:
      - 'test_mariadb_data:/var/lib/mysql'
    ports:
      - "3307:3306"
  postgresql:
    image: docker.io/bitnami/postgresql
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_sonarqube
      - POSTGRESQL_DATABASE=bitnami_sonarqube
  sonarqube:
    image: docker.io/bitnami/sonarqube
    ports:
      - '9000:9000'
    volumes:
      - 'sonarqube_data:/bitnami/sonarqube'
    depends_on:
      - postgresql
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - SONARQUBE_DATABASE_HOST=postgresql
      - SONARQUBE_DATABASE_PORT_NUMBER=5432
      - SONARQUBE_DATABASE_USER=bn_sonarqube
      - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
volumes:
  mariadb_data:
    driver: local
  test_mariadb_data:
    driver: local
  postgresql_data:
    driver: local
  sonarqube_data:
    driver: local
